apiVersion: v1
kind: Pod
metadata:
  name: ex-app-pod
  labels:
    name: ex-app-pod
    app: demo-randoms-app
spec:
  containers:
    - name: ex-app
      image: leanm/ex:latest
      ports:
        - containerPort: 3001
      env:
        - name: NUMEX_PORT
          value: "3001"
