apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-deploy
  labels:
    app: "ex-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ex-app"
  template:
    metadata:
      labels:
        app: "ex-app"
    spec:
      containers:
        - name: "ex-app"
          image: leanm/ex:latest
          ports:
            - containerPort: 3001
          env:
            - name: NUMEX_PORT
              value: "3001"

---
apiVersion: v1
kind: Service
metadata:
  name: "ex-app"
  labels:
    app: "ex-app"
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: "ex-app"
