apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
  labels:
    name: php-deploy
    app: demo-randoms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: php-app-pod
      app: demo-randoms-app
  template:
    metadata:
      name: php-app-pod
      labels:
        name: php-app-pod
        app: demo-randoms-app
    spec:
      containers:
        - name: num-php
          image: leanm/ph:latest
          ports:
            - containerPort: 3002
          env:
            - name: NUMPH_PORT
              value: "3002"
