apiVersion: apps/v1
kind: Deployment
metadata:
  name: "php-app"
  labels:
    app: "php-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "php-app"
  template:
    metadata:
      labels:
        app: "php-app"
    spec:
      containers:
        - name: num-php
          image: leanm/ph:latest
          ports:
            - containerPort: 3002
          env:
            - name: NUMPH_PORT
              value: "3002"

---
apiVersion: v1
kind: Service
metadata:
  name: "php-app"
  labels:
    app: "php-app"
spec:
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: "php-app"
