apiVersion: v1
kind: Service
metadata:
  name: random-service
  labels:
    name: random-service
    app: demo-randoms-app
spec:
  type: IngressClass
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    name: random-app-pod
    app: demo-randoms-app
