apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-app
  labels:
    app: random-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-app
  template:
    metadata:
      labels:
        app: random-app
    spec:
      containers:
        - name: num-random
          image: leanm/randoms:latest
          ports:
            - containerPort: 3000
          env:
            - name: NUMRE_PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: random-app
  labels:
    app: random-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: random-app
