apiVersion: v1
kind: Pod
metadata:
  name: random-app-pod
  labels:
    name: random-app-pod
    app: demo-randoms-app
spec:
  containers:
    - name: num-random
      image: leanm/randoms:latest
      ports:
        - containerPort: 3000
      env:
        - name: NUMRE_PORT
          value: "3000"
