server:
  port: 9999
zuul:
  routes:
    php:
      path: /php/**
      url: http://php-app-service:3002/
    express:
      path: /express/**
      url: http://ex-app-service:3001/
    python:
      path: /python/**
      url: http://py-app-service:3003/
