server:
  port: 9999
zuul:
  routes:
    auth:
      path: /auth/**
      url: http://auth-service:8080/
    search:
      path: /search/**
      url: http://search-service:8081/
    review:
      path: /review/**
      url: http://review-service:8082/
    matching:
      path: /matching/**
      url: http://matching-service:8083/
