server:
  port: 9999
zuul:
  routes:
    php:
      path: /php/**
      url: http://php-app:3002/
    express:
      path: /express/**
      url: http://ex-app:3001/
    python:
      path: /python/**
      url: http://py-app:3003
